version: "3.9"

services:
  qwise-app:
    image: qwise-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app-container
    ports:
      - "7775:7775"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${PROD_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
      - LOG_PATH=${PROD_LOG_PATH}
      - PROD_GOOGLE_CLIENT_ID=${PROD_GOOGLE_CLIENT_ID}
      - PROD_GOOGLE_CLIENT_SECRET=${PROD_GOOGLE_CLIENT_SECRET}
      - PROD_GMAIL_USERNAME=${PROD_GMAIL_USERNAME}
      - PROD_GMAIL_APP_PASSWORD=${PROD_GMAIL_APP_PASSWORD}
      - PROD_MINIO_ACCESS_KEY=${PROD_MINIO_ACCESS_KEY}
      - PROD_MINIO_SECRET_KEY=${PROD_MINIO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-net
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:latest
    container_name: qwise-db-container
    environment:
      POSTGRES_DB: qwise-db
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - shared-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "qwise-user", "-d", "qwise-db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: minio-server
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${PROD_MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${PROD_MINIO_SECRET_KEY}
    volumes:
      - minio_data:/minio-data
    command: server /data --console-address ":9001"
    networks:
      - shared-net

volumes:
  db_data:
  logs:
networks:
  shared-net:
    driver: bridge
