spring:
  application:
    name: qwise
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${PROD_GOOGLE_CLIENT_ID}
            client-secret: ${PROD_GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "https://qwise.codepays.dev/login/oauth2/code/google"
            client-name: Google
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${PROD_GMAIL_USERNAME}
    password: ${PROD_GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  url: qwise.codepays.dev
  port: 9000
  access-key: ${PROD_MINIO_ROOT_USER}
  secret-key: ${PROD_MINIO_ROOT_PASSWORD}
  secure: true
  buckets:
    question-images: question-images
    user-profiles: user-avatars
    thumbnail_images: thumbnail_images

logging:
  level:
    root: INFO
  file:
    path: ${LOG_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "info, health, metrics, prometheus"
  endpoint:
    health:
      show-details: never

jwt:
  expirationMs: 3600000

server:
  port: 7775