spring:
  application:
    name: qwise
  datasource:
    url: jdbc:postgresql://localhost:5432/qwise_db
    username: guest
    password: guest123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "http://localhost:7775/login/oauth2/code/google"
            client-name: Google
  mail:
    host: smtp.gmail.com
    port: 587
    username: qwisecompany@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  url: localhost
  port: 9000
  access-key: admin
  secret-key: admin123
  secure: false
  buckets:
    question-images: question-images
    user-profiles: user-avatars
    thumbnail_images: thumbnail_images


jwt:
  expirationMs: 3600000

server:
  port: 7775